on:
  push:
    branches:
      - master
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Release
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$GPG_SECRET_PASSPHRASE" --output .github/workflows/secring .github/workflows/secring.gpg
          gpg --import --batch .github/workflows/secring
          export GPG_TTY=$(tty)
          echo ossrhUsername=eller86 >> gradle.properties
          echo "ossrhPassword=${SONATYPE_PASSWORD}" >> gradle.properties
          echo "signing.gnupg.keyName=${SIGNING_KEY_ID}" >> gradle.properties
          echo "signing.gnupg.passphrase=${SIGNING_PASSWORD}" >> gradle.properties
          echo "signing.gnupg.executable=gpg" >> gradle.properties
#          ./gradlew publish --no-daemon
        env:
          GPG_SECRET_PASSPHRASE: ${{ secrets.GPG_SECRET_PASSPHRASE }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
